export const SET_ALL_CLIENT="SET_ALL_CLIENT";
export const SET_CLIENT_NAME="SET_CLIENT_NAME";
export const SET_CLIENT_PROFILE="SET_CLIENT_PROFILE";
export const SET_CLIENT_EMAIL="SET_CLIENT_EMAIL";
export const SET_CLIENT_PASSWORD="SET_CLIENT_PASSWORD";
export const SET_CLIENT_POSITION="SET_CLIENT_POSITION";
export const SET_CLIENT_DEPARTMENT="SET_CLIENT_DEPARTMENT";
export const SET_CLIENT_EMPLOYEE_ID="SET_CLIENT_EMPLOYEE_ID";
export const RESET_CLIENT="RESET_CLIENT";
export const SELECT_OPTION = "SELECT_OPTION";
export const SET_CLIENT_CONTACT_NUM="SET_CLIENT_CONTACT_NUM";
export const SET_CLIENT_ADDRESS="SET_CLIENT_ADDRESS";
export const SET_CLIENT_PAN_NUM="SET_CLIENT_PAN_NUM";
export const SET_CLIENT_AADHAR_NUM="SET_CLIENT_AADHAR_NUM";
export const SET_CLIENT_CLIENT_SOURCE="SET_CLIENT_CLIENT_SOURCE";
export const RESET_CLIENT="RESET_CLIENT";

